// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-TQ95wF5Zq0Q_9t-FL5uxuukI5lHVTsI',
    appId: '1:942823924996:web:de3ad57bdbaf7432f89c51',
    messagingSenderId: '942823924996',
    projectId: 'startflutter-709e5',
    authDomain: 'startflutter-709e5.firebaseapp.com',
    storageBucket: 'startflutter-709e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWmA5vRDkd4Ayg82DgCU8oSyvPUywtNr4',
    appId: '1:942823924996:android:4f67d9dcaf28637af89c51',
    messagingSenderId: '942823924996',
    projectId: 'startflutter-709e5',
    storageBucket: 'startflutter-709e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDHsFawiWE6WOJgAmJWDLr5DPaxixvFw',
    appId: '1:942823924996:ios:9b79c747f7202874f89c51',
    messagingSenderId: '942823924996',
    projectId: 'startflutter-709e5',
    storageBucket: 'startflutter-709e5.appspot.com',
    iosClientId: '942823924996-e6rj0v7aoenq548bn67qkai71nd32ucf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDHsFawiWE6WOJgAmJWDLr5DPaxixvFw',
    appId: '1:942823924996:ios:9b79c747f7202874f89c51',
    messagingSenderId: '942823924996',
    projectId: 'startflutter-709e5',
    storageBucket: 'startflutter-709e5.appspot.com',
    iosClientId: '942823924996-e6rj0v7aoenq548bn67qkai71nd32ucf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
